### ISSUE TITLE
Would you like to upload a local txt for the codes replicating BBE?

### ISSUE THREAD

**Issue by ctex77** [PetrGarm/FAVAR#1]
Dear PetrGarm,
Thank you for sharing your code replicating BBE. But it seems to use your local data by "df <- read.table("C:/Users/petrg/Desktop/ЦМП/BBE_Ddisk/BBE_Ddisk/2step/nsbalpanel.txt")". So would you like to upload it at your convenience?

**Comment by PetrGarm** [comment]
https://github.com/PetrGarm/FAVAR/commit/f10670318587c2e0b017a1a7a44d09734a32409e

Done
